name: CI

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: npm ci
            - run: npm run lint
            - run: npm run prettier:lint

    build:
        runs-on: ubuntu-latest

        needs: lint

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 10
            - run: npm ci
            - run: npm run build
              env:
                  CI: true
            - uses: actions/upload-artifact@v1
              with:
                  name: build
                  path: dist

    deploy:
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'

        needs: build

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/download-artifact@v1
              with:
                  name: build
            - run: sudo apt-get update --fix-missing
            - run: sudo apt-get install --fix-missing ncftp
            - shell: bash
              env:
                  FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
                  FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
                  FTP_HOST: ${{ secrets.FTP_HOST }}
              run: ncftpput -R -v -u "$FTP_USERNAME" -p "$FTP_PASSWORD" "$FTP_HOST" / build/needlework-canvas/*
